"""Orchestrates the end-to-end ETL flow."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .configuration import OutputsConfig
from .io_handlers import DataLoader, DataWriter
from .transformer import FondequipTransformer


@dataclass
class ETLResult:
    """Stores the paths generated by the pipeline."""

    clean_table: Path
    summary_by_region: Path
    summary_by_type: Path
    summary_by_year: Path


class ETLPipeline:
    """Pipeline that honours SRP by delegating to dedicated collaborators."""

    def __init__(
        self,
        loader: DataLoader,
        transformer: FondequipTransformer,
        writer: DataWriter,
        outputs: OutputsConfig,
    ) -> None:
        self._loader = loader
        self._transformer = transformer
        self._writer = writer
        self._outputs = outputs

    def run(self) -> ETLResult:
        raw = self._loader.load()
        clean = self._transformer.clean(raw)

        region = self._transformer.summarize_by_region(clean)
        equip_type = self._transformer.summarize_by_type(clean)
        year = self._transformer.summarize_by_year(clean)

        clean_path = self._writer.write(clean, self._outputs.clean_table)
        region_path = self._writer.write(region, self._outputs.summary_by_region)
        type_path = self._writer.write(equip_type, self._outputs.summary_by_type)
        year_path = self._writer.write(year, self._outputs.summary_by_year)

        return ETLResult(
            clean_table=clean_path,
            summary_by_region=region_path,
            summary_by_type=type_path,
            summary_by_year=year_path,
        )
